export type {
  ColumnId,
  DataSetId,
  Column,
  ColumnSettings,
  CellValue,
  TypedDataSet,
  TypedRow,
  DataSet,
  DatasetContract,
} from "./dataset/types.js";
export { ColumnType, dataSetId, columnId } from "./dataset/types.js";

export type { DataSetOp } from "./dataset/ops.js";
export { applyOps, validateOpOrder } from "./dataset/ops.js";

export type { DataSetLookup } from "./dataset/lookup.js";
export { createLookup } from "./dataset/lookup.js";

export {
  type ExternalDataSetDef,
  type ExternalColumnDef,
  type DataRequest,
  type FetchResult,
  type DataProvider,
  type DataProviderConfig,
  type WebSocketAuthConfig,
  type ExtractionPreset,
  type PresetRegistry,
  type ExtractionResult,
  type ResolveResult,
  type PagesDataMessage,
  type ServiceCapabilities,
  HttpMethod,
  LOCAL_CAPABILITIES,
  isServiceCapabilities,
  type ParsedExternalDataSetDef,
  parseExternalDataSetDef,
  type CsvParseOptions,
  type CsvParseResult,
  parseCsv,
  parseMetrics,
  createPresetRegistry,
  extractDataSet,
  evaluateGenerator,
  joinDataSets,
  type ResolverContext,
  resolveExternalDataSet,
  InlineProvider,
  CorsProxyProvider,
  BrowserFetchProvider,
  ServerRelayProvider,
  ServerQueryClient,
  PostMessageProvider,
  createDataProviderFactory,
  type DataProviderFactory,
  type PushSource,
  type PushSourceConfig,
  type PushSourceError,
  buildConnectionUrl,
  sendListen,
  sendUnlisten,
  dispatchWireEvent,
  createWebSocketSource,
  createSseSource,
  SSEManager,
  type SSEEvent,
  type SSEHandler,
  type SSESubscribeOptions,
  createPushPool,
  type PushPool,
  type EventConnection,
  type ListenAck,
  type ConnectionStatus,
  type EventConnectionOptions,
  createEventConnection,
  isValidTopicOrPattern,
  matchesTopic,
  isMatchedByRegistrations,
} from "./dataset/external/index.js";

