import { z } from "zod";
import {
  barChartPropsSchema, lineChartPropsSchema, areaChartPropsSchema,
  pieChartPropsSchema, scatterChartPropsSchema, bubbleChartPropsSchema,
  timeseriesPropsSchema, heatmapChartPropsSchema, treemapChartPropsSchema,
  densityHeatmapPropsSchema, metricGridPropsSchema,
  dataTablePropsSchema, gridTablePropsSchema,
  metricPropsSchema, meterPropsSchema, selectorPropsSchema,
  mapPropsSchema, badgePropsSchema, countdownPropsSchema,
  timelinePropsSchema, graphPropsSchema, eventTimelinePropsSchema,
  groupedViewPropsSchema,
  gridPropsSchema, columnsPropsSchema, rowsPropsSchema, stackPropsSchema,
  tabsPropsSchema, pillsPropsSchema, sidebarPropsSchema, treePropsSchema,
  menuPropsSchema, accordionPropsSchema, carouselPropsSchema,
  splitPropsSchema, dockBarPropsSchema, hostPanelPropsSchema,
  floatingWorkspacePropsSchema,
  panelPropsSchema, htmlPropsSchema, markdownPropsSchema, titlePropsSchema,
  lazyPagePropsSchema, pagePropsSchema,
  textInputPropsSchema, numberInputPropsSchema, dropdownPropsSchema,
  checkboxPropsSchema, datePickerPropsSchema, textareaPropsSchema,
  schemaFormPropsSchema, actionButtonPropsSchema,
  formScopePropsSchema, submitButtonPropsSchema,
  iframePluginPropsSchema,
} from "./component-schemas.js";

export const componentSchemaRegistry: ReadonlyMap<string, z.ZodType> = new Map([
  ["grid", gridPropsSchema],
  ["columns", columnsPropsSchema],
  ["rows", rowsPropsSchema],
  ["stack", stackPropsSchema],
  ["tabs", tabsPropsSchema],
  ["pills", pillsPropsSchema],
  ["sidebar", sidebarPropsSchema],
  ["tree", treePropsSchema],
  ["menu", menuPropsSchema],
  ["accordion", accordionPropsSchema],
  ["carousel", carouselPropsSchema],
  ["split", splitPropsSchema],
  ["dock-bar", dockBarPropsSchema],
  ["host-panel", hostPanelPropsSchema],
  ["floating-workspace", floatingWorkspacePropsSchema],
  ["panel", panelPropsSchema],
  ["html", htmlPropsSchema],
  ["markdown", markdownPropsSchema],
  ["title", titlePropsSchema],
  ["lazy-page", lazyPagePropsSchema],
  ["page", pagePropsSchema],
  ["bar-chart", barChartPropsSchema],
  ["line-chart", lineChartPropsSchema],
  ["area-chart", areaChartPropsSchema],
  ["pie-chart", pieChartPropsSchema],
  ["scatter-chart", scatterChartPropsSchema],
  ["bubble-chart", bubbleChartPropsSchema],
  ["timeseries", timeseriesPropsSchema],
  ["heatmap-chart", heatmapChartPropsSchema],
  ["treemap-chart", treemapChartPropsSchema],
  ["density-heatmap", densityHeatmapPropsSchema],
  ["metric-grid", metricGridPropsSchema],
  ["data-table", dataTablePropsSchema],
  ["grid-table", gridTablePropsSchema],
  ["metric", metricPropsSchema],
  ["meter", meterPropsSchema],
  ["selector", selectorPropsSchema],
  ["map", mapPropsSchema],
  ["badge", badgePropsSchema],
  ["countdown", countdownPropsSchema],
  ["timeline", timelinePropsSchema],
  ["graph", graphPropsSchema],
  ["event-timeline", eventTimelinePropsSchema],
  ["grouped-view", groupedViewPropsSchema],
  ["iframe-plugin", iframePluginPropsSchema],
  ["input", textInputPropsSchema],
  ["number-input", numberInputPropsSchema],
  ["select", dropdownPropsSchema],
  ["checkbox", checkboxPropsSchema],
  ["date-picker", datePickerPropsSchema],
  ["textarea", textareaPropsSchema],
  ["schema-form", schemaFormPropsSchema],
  ["action-button", actionButtonPropsSchema],
  ["form-scope", formScopePropsSchema],
  ["submit-button", submitButtonPropsSchema],
]);
